include: package:lints/recommended.yaml
analyzer:
  strong-mode:
    implicit-casts: false
linter:
  rules:
    - avoid_annotating_with_dynamic
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - empty_constructor_bodies
    - no_duplicate_case_values
    - null_closures
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_final_locals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_null_aware_operators
    - prefer_relative_imports
    - prefer_void_to_null
    - recursive_getters
    - slash_for_doc_comments
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - valid_regexps
